### ISSUE TITLE
documentation: gitbook

### ISSUE THREAD

**Issue by leemlwando** [microtechcloudsolutions/sms-gateway#10]
Service Descriptions, phases , project setup and workflow will b documented on gitbook.
writers needed.
skills needed:
- markdown

**Comment by OlivierJM** [comment]
kindly add a note on where the docs are currently, though I don't know much of the contents that needs to be added but I will help out with the markdown.

**Comment by leemlwando** [comment]
> 
> 
> kindly add a note on where the docs are currently, though I don't know much of the contents that needs to be added but I will help out with the markdown.

Alright. i acm closing this issue and opening a new one; an official call for writers
