### ISSUE TITLE
set up rabbit mq

### ISSUE THREAD

**Issue by microtechcloud** [microtechcloudsolutions/sms-gateway#6]
set up rabbitmq as message broker and queue management

**Comment by OlivierJM** [comment]
@joebbrien would you like to work on this, to help set up the **rabbit mq** ?

**Comment by Joebbrien** [comment]
If I have info on what needs to be built I would love to chimp in

**Comment by microtechcloud** [comment]
@OlivierJM @Joebbrien will post full service specs soon. will mention you in comments

**Comment by OlivierJM** [comment]
Cool, I am sure @Joebbrien  will be able to help on this one.

**Comment by leemlwando** [comment]
@Joebbrien @OlivierJM  closing this issue and reoponing a new one following up on @OlivierJM advice to provide documentation upfront to guide contributors
